defaults:
  - rl_evaluation
  - _self_

evaluation:
  loading:
    tickers:
      - AAPL
  preprocessing:
    technical_indicators:
      - log_return_0
      - log_return_1
      - log_return_2
      - log_return_3
      - log_return_4
      - log_return_5
      - log_return_6
      - log_return_7
      - log_return_8
      - log_return_9
    start_date: ${evaluation.environment.start_date}
    end_date: ${evaluation.environment.end_date}
  environment:
    _target_: environment.utils.create_signal_action_env
    start_date: 2023-01-01
    end_date: 2025-01-01
    cash: 10000.0

run_parameters:
  seed: 0
  device: null

policy:
  model_path: null
