# Global image definition
image: python:3.10

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

Run requirements check:
  stage: test
  only:
    - merge_requests
  script:
    - bash tools/ci/run_requirements_check.sh

Code check:
  stage: test
  needs: ["Run requirements check"]
  only:
    - merge_requests
  script:
    - bash tools/ci/run_style.sh

Run pytest:
  stage: test
  needs: ["Run requirements check"]
  only:
    - merge_requests
  script:
    - bash tools/ci/run_pytest.sh
# run:
#   script:
#     - pip install .
#     # run the command here
#   artifacts:
#     paths:
#       - build/*

# pages:
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd doc
#     - make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
