[tool.isort]
profile = "black"
known_third_party = ["wandb"]
line_length = 88

[project]
name = "Finance"
version = "0.0.0"
description = "Private package to have fun around finance."
authors = [{ name = "Yann POURCENOUX", email = "yann.pourcenoux@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
urls = { Homepage = "https://gitlab.com/yannpourcenoux/Finance" }
dependencies = [
    "altair~=5.3.0",
    "GitPython~=3.1.43",
    "hydra-core~=1.3.2",
    "jupyter~=1.0.0",
    "loguru~=0.7.2",
    "numpy~=2.0.1",
    "pandas~=2.2.2",
    "plotly~=5.23.0",
    "pydantic~=2.8.2",
    "python-dotenv~=1.0.1",
    "quantstats-lumi~=0.3.3",
    "seaborn~=0.13.2",
    "statsmodels~=0.14.2",
    "stockstats~=0.6.2",
    "streamlit~=1.37.0",
    "tensordict~=0.5.0",
    "torchrl~=0.5.0",
    "torch==2.4.0",
    "tqdm~=4.66.4",
    "wandb~=0.17.5",
    "yfinance~=0.2.41",
]

[project.optional-dependencies]
dev = [
    "docformatter~=1.7.5",
    "icecream~=2.1.3",
    "isort~=5.13.2",
    "pre-commit~=3.8.0",
    "prettier~=0.0.7",
    "pytest~=8.3.2",
    "ruff~=0.5.5",
]

[project.scripts]
run_training = "run_training:main"
