[tool.isort]
profile = "black"
known_third_party = ["wandb"]
line_length = 88

[project]
name = "Finance"
version = "0.0.0"
description = "Private package to have fun around finance."
authors = [{ name = "Yann POURCENOUX", email = "yann.pourcenoux@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
urls = { Homepage = "https://gitlab.com/yannpourcenoux/Finance" }
dependencies = [
    'GitPython~=3.1.42',
    'hydra-core~=1.3.2',
    'jupyter~=1.0.0',
    'loguru~=0.7.2',
    'quantstats-lumi~=0.3.1',
    'pandas~=2.2.1',
    'plotly~=5.20.0',
    'pydantic~=2.6.4',
    'python-dotenv~=1.0.1',
    'seaborn~=0.13.2',
    'statsmodels~=0.14.1',
    'stockstats~=0.6.2',
    'tensordict~=0.4.0',
    'torchrl~=0.4.0',
    'torch~=2.3.1',
    'tqdm~=4.66.4',
    'wandb~=0.16.4',
    'yfinance~=0.2.37',
]

[project.optional-dependencies]
dev = [
    'black~=23.7.0',
    'docformatter~=1.7.5',
    'icecream~=2.1.3',
    'isort~=5.12.0',
    'pre-commit~=3.3.3',
    'prettier~=0.0.7',
    'pytest~=8.1.1',
    'ruff~=0.0.280',
]
