defaults:
  - quant_experiment
  - _self_

agent:
  algorithm_name: BuyOneShareEveryDay

logging:
  online: False

eval_environment:
  cash: 100000.0
  start_date: 2021-01-01
  end_date: 2023-01-01

preprocessing:
  technical_indicators:
    - log_return_0
    - log_return_1
    - log_return_2
  start_date: "2021-01-01"

loading:
  tickers:
    - AAPL
    - MSFT
