defaults:
  - base_experiment
  - _self_

loading:
  tickers:
    - COS_10

agent:
  hidden_sizes:
    - 16
train_environment:
  batch_size: 128

collector:
  frames_per_batch: 5000
  total_frames: -1

training:
  num_epochs: 100
  num_steps_per_epoch: 1000

replay_buffer:
  buffer_size: 10000000
  batch_size: 128
  buffer_scratch_dir: /workspaces/Finance/outputs/scratch

evaluation:
  eval_rollout_steps: 10000

optimizer:
  actor_lr: 1e-3
  critic_lr: 1e-3
  alpha_lr: 1e-3

preprocessing:
  technical_indicators:
    - log-ret
    - log-ret_-1_s
    - log-ret_-2_s
    - log-ret_-3_s
    - log-ret_-4_s
    - log-ret_-5_s
    - log-ret_-6_s
    - log-ret_-7_s
    - log-ret_-8_s
    - log-ret_-9_s
  start_date: 2000-01-01

rest:
  device: cuda
  seed: 0
