defaults:
  - base_experiment
  - eval_environment: same_time_train
  - preprocessing: all
  - _self_

loading:
  tickers:
    - AAPL
    - GOOGL

train_environment:
  cash: 1000.0
  start_date: 2021-01-01
  end_date: 2023-01-01

training:
  num_epochs: 100
  num_steps_per_epoch: 1000

replay_buffer:
  batch_size: 512

optimizer:
  actor_lr: 1e-3

logging:
  project: double-ticker-experiment
