defaults:
  - base_experiment
  - _self_

loading:
  tickers:
    - AAPL

train_environment:
  cash: 1000.0
  start_date: 2021-01-01
  end_date: 2023-01-01

training:
  num_epochs: 100
  num_steps_per_epoch: 1000

replay_buffer:
  batch_size: 512

optimizer:
  actor_lr: 1e-3

logging:
  project: single-ticker-experiment

preprocessing:
  technical_indicators:
    - log-ret
    - log-ret_-1_s
    - log-ret_-2_s
    - log-ret_-3_s
    - log-ret_-4_s
    - log-ret_-5_s
    - log-ret_-6_s
    - log-ret_-7_s
    - log-ret_-8_s
    - log-ret_-9_s
