name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read Python version
        id: python-version
        run: echo "version=$(cat .python-version | tr -d ' \n')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Download test data
        run: |
          mkdir -p data
          uv run run_download --files src/data/cfg/test_data.json

      - name: Run tests
        run: |
          uv run pytest -n auto src
